import { CognitiveGameDefinition, PatientMoodType, GameCategory } from '../types';

export const COGNITIVE_GAMES_CATALOG: CognitiveGameDefinition[] = [
  {
    id: 'game-01',
    gameKey: 'MEMORY_HERITAGE',
    index: 1,
    title: 'Heritage Memory Match',
    subtitle: 'Pair familiar cultural treasures & festival symbols',
    category: 'MEMORY',
    targetDomain: 'Visual Working Memory',
    culturalTheme: 'Assam & NER Heritage',
    color: 'amber',
    bgGradient: 'from-amber-500 to-amber-700',
    iconName: 'Brain',
    recommendedForMoods: ['HAPPY', 'CALM', 'NEUTRAL'],
    baseDifficulty: 2,
    description: 'Turn cards to find matching pairs of cultural items like the Bihu Dhol, Assam Tea Leaf, and Gamosa.',
    instructions: 'Tap any card to reveal its image, then find its identical twin partner.',
  },
  {
    id: 'game-02',
    gameKey: 'ATTENTION_WILDLIFE',
    index: 2,
    title: 'Kaziranga Wildlife Spotlight',
    subtitle: 'Spot target animals & birds in natural sanctuaries',
    category: 'ATTENTION',
    targetDomain: 'Selective & Focused Attention',
    culturalTheme: 'Kaziranga & Manas National Parks',
    color: 'teal',
    bgGradient: 'from-teal-500 to-teal-700',
    iconName: 'Eye',
    recommendedForMoods: ['HAPPY', 'CALM', 'NEUTRAL'],
    baseDifficulty: 2,
    description: 'Find the one-horned rhino, great hornbill, and singing myna bird hidden in the lush grassland.',
    instructions: 'Look at the target animal shown at the top and tap it when it appears.',
  },
  {
    id: 'game-03',
    gameKey: 'PATTERN_WEAVER',
    index: 3,
    title: 'Traditional Motif Weaver',
    subtitle: 'Complete handloom diamond & silk border sequences',
    category: 'PATTERN',
    targetDomain: 'Inductive Logic & Working Memory',
    culturalTheme: 'Sualkuchi Silk & Handlooms',
    color: 'indigo',
    bgGradient: 'from-indigo-500 to-indigo-700',
    iconName: 'Layers',
    recommendedForMoods: ['HAPPY', 'CALM', 'NEUTRAL'],
    baseDifficulty: 2,
    description: 'Follow the traditional loom sequence of Muga gold, red diamond weaves, and river lotus prints.',
    instructions: 'Look at the pattern in the woven fabric and tap the piece that comes next.',
  },
  {
    id: 'game-04',
    gameKey: 'ROUTINE_SEQUENCER',
    index: 4,
    title: 'Daily ADL Routine Sequencer',
    subtitle: 'Arrange everyday living steps in natural order',
    category: 'ROUTINE',
    targetDomain: 'Executive Function & Procedural Memory',
    culturalTheme: 'Daily Courtyard & Morning Life',
    color: 'emerald',
    bgGradient: 'from-emerald-500 to-emerald-700',
    iconName: 'CalendarCheck',
    recommendedForMoods: ['CALM', 'NEUTRAL', 'ANXIOUS'],
    baseDifficulty: 1,
    description: 'Organize morning tea, watering garden plants, and taking morning medication in proper sequence.',
    instructions: 'Tap the steps in the order you naturally perform them throughout the day.',
  },
  {
    id: 'game-05',
    gameKey: 'LANGUAGE_PROVERB',
    index: 5,
    title: 'Word & Regional Proverb Recall',
    subtitle: 'Fill in missing words in beloved timeless folk sayings',
    category: 'LANGUAGE',
    targetDomain: 'Semantic Language & Word Retrieval',
    culturalTheme: 'Assamese & North East Proverbs (Dakor Boson)',
    color: 'rose',
    bgGradient: 'from-rose-500 to-rose-700',
    iconName: 'MessageSquare',
    recommendedForMoods: ['HAPPY', 'CALM', 'NEUTRAL'],
    baseDifficulty: 2,
    description: 'Remember classic sayings about nature, patience, harvest, and family joy.',
    instructions: 'Read the gentle sentence and select the correct word that completes the phrase.',
  },
  {
    id: 'game-06',
    gameKey: 'SPATIAL_SORTER',
    index: 6,
    title: 'Nature & Kitchen Category Sorter',
    subtitle: 'Sort orchard fruits, spices, and cooking brass utensils',
    category: 'SPATIAL',
    targetDomain: 'Conceptual Categorization & Mental Flexibility',
    culturalTheme: 'Village Hearth & Garden Orchards',
    color: 'cyan',
    bgGradient: 'from-cyan-500 to-cyan-700',
    iconName: 'FolderTree',
    recommendedForMoods: ['HAPPY', 'CALM', 'NEUTRAL'],
    baseDifficulty: 2,
    description: 'Place fresh garden vegetables, tea leaves, and traditional kitchen vessels in their rightful basket.',
    instructions: 'Tap each item and place it in the correct group (Kitchen vs Garden).',
  },
  {
    id: 'game-07',
    gameKey: 'STORY_VIGNETTES',
    index: 7,
    title: 'Story & Photo Memory Vignettes',
    subtitle: 'Look at a warm memory photo and recall gentle details',
    category: 'STORY',
    targetDomain: 'Episodic Memory & Reminiscence',
    culturalTheme: 'Family Milestones & Celebrations',
    color: 'violet',
    bgGradient: 'from-violet-500 to-violet-700',
    iconName: 'BookOpenCheck',
    recommendedForMoods: ['CALM', 'SAD', 'NEUTRAL'],
    baseDifficulty: 1,
    description: 'Observe a beautiful vintage tea estate or festival photo, then answer comforting questions.',
    instructions: 'Enjoy the photo, take your time, and tap the answer that matches what you see.',
  },
  {
    id: 'game-08',
    gameKey: 'RELAXATION_FLUTE',
    index: 8,
    title: 'Peaceful Flute & Breathing Soundscape',
    subtitle: 'Gentle auditory relaxation with diaphragmatic breathing',
    category: 'RELAX',
    targetDomain: 'Emotional Regulation & Sundowning Relief',
    culturalTheme: 'Bamboo Woodwinds & Flowing River',
    color: 'orange',
    bgGradient: 'from-orange-500 to-orange-700',
    iconName: 'Heart',
    recommendedForMoods: ['ANXIOUS', 'TIRED', 'SAD', 'CALM'],
    baseDifficulty: 1,
    description: 'Listen to soothing bamboo melodies while watching a peaceful breathing lotus expand and contract.',
    instructions: 'Breathe in as the lotus blossoms, and gently exhale as it closes.',
  },
  {
    id: 'game-09',
    gameKey: 'PUZZLE_MAJULI',
    index: 9,
    title: 'Majuli Mask & Pottery Assembly',
    subtitle: 'Assemble authentic craft pieces into complete art',
    category: 'PUZZLE',
    targetDomain: 'Visuospatial Construction & Part-Whole Synthesis',
    culturalTheme: 'Majuli Island Satra Crafts',
    color: 'sky',
    bgGradient: 'from-sky-500 to-sky-700',
    iconName: 'Puzzle',
    recommendedForMoods: ['HAPPY', 'CALM', 'NEUTRAL'],
    baseDifficulty: 2,
    description: 'Reconstruct traditional Majuli bamboo masks and clay tea pots piece by piece.',
    instructions: 'Tap the puzzle pieces to assemble the sacred craft in its outline.',
  },
  {
    id: 'game-10',
    gameKey: 'MOTOR_REFLEX',
    index: 10,
    title: 'Tea Garden Leaf & Bihu Reflex Catcher',
    subtitle: 'Gentle tap timing when golden leaves touch the basket',
    category: 'MOTOR',
    targetDomain: 'Visuomotor Coordination & Reaction Inhibition',
    culturalTheme: 'Morning Tea Plucking in Jorhat',
    color: 'emerald',
    bgGradient: 'from-emerald-500 to-emerald-700',
    iconName: 'Zap',
    recommendedForMoods: ['HAPPY', 'CALM'],
    baseDifficulty: 2,
    description: 'Tap the basket gently when fresh green tea leaves drift into the center target.',
    instructions: 'Watch the gentle leaf float down and tap the screen right when it aligns with the basket.',
  },
  {
    id: 'game-11',
    gameKey: 'CALC_MARKET',
    index: 11,
    title: 'Assam Market Currency & Coin Counter',
    subtitle: 'Count colorful coins & notes for fresh vegetables',
    category: 'SPATIAL',
    targetDomain: 'Mental Calculation & Number Recognition',
    culturalTheme: 'Weekly Haat & Local Village Bazaar',
    color: 'amber',
    bgGradient: 'from-amber-600 to-orange-600',
    iconName: 'Coins',
    recommendedForMoods: ['HAPPY', 'CALM'],
    baseDifficulty: 2,
    description: 'Select exact change (₹10, ₹20, ₹50) to purchase sweet bananas and fresh mint.',
    instructions: 'Tap the coins that add up to the requested bazaar price.',
  },
  {
    id: 'game-12',
    gameKey: 'GEO_EXPLORER',
    index: 12,
    title: 'North East Regional Map Explorer',
    subtitle: 'Recognize famous landmarks from Brahmaputra to Cherrapunji',
    category: 'SPATIAL',
    targetDomain: 'Spatial Orientation & Geographic Memory',
    culturalTheme: 'Seven Sisters & Brahmaputra Geography',
    color: 'teal',
    bgGradient: 'from-teal-600 to-cyan-700',
    iconName: 'Compass',
    recommendedForMoods: ['CALM', 'HAPPY', 'NEUTRAL'],
    baseDifficulty: 2,
    description: 'Match famous North Eastern hill towns, bridges, and waterfalls to their regions.',
    instructions: 'Look at the landmark photo and choose which famous valley or hill town it belongs to.',
  },
  {
    id: 'game-13',
    gameKey: 'AUDIO_INSTRUMENT',
    index: 13,
    title: 'Traditional Instrument Sound Identifier',
    subtitle: 'Listen to gentle rhythms of Dhol, Pepa, Gogona & Flute',
    category: 'LANGUAGE',
    targetDomain: 'Auditory Perception & Acoustic Timbre',
    culturalTheme: 'North Eastern Folk Instruments',
    color: 'indigo',
    bgGradient: 'from-indigo-600 to-purple-700',
    iconName: 'Music',
    recommendedForMoods: ['HAPPY', 'CALM', 'SAD'],
    baseDifficulty: 1,
    description: 'Listen to a short melody soundbite and identify the handcrafted instrument playing it.',
    instructions: 'Tap the speaker to hear the acoustic note, then tap the matching instrument.',
  },
  {
    id: 'game-14',
    gameKey: 'TEMPORAL_CALENDAR',
    index: 14,
    title: 'Seasonal Harvest & Farming Calendar',
    subtitle: 'Connect spring sowing, monsoons, and winter harvesting',
    category: 'ROUTINE',
    targetDomain: 'Temporal Orientation & Chronological Reasoning',
    culturalTheme: 'Bihu Seasons (Bohag, Kati, Magh)',
    color: 'emerald',
    bgGradient: 'from-emerald-600 to-teal-700',
    iconName: 'Sun',
    recommendedForMoods: ['CALM', 'NEUTRAL'],
    baseDifficulty: 2,
    description: 'Arrange seasonal activities like seed planting, summer rains, and bonfire winter feasts.',
    instructions: 'Place the seasonal farming traditions in their natural yearly order.',
  },
  {
    id: 'game-15',
    gameKey: 'FACE_KINSHIP',
    index: 15,
    title: 'Family Face & Kinship Recognition',
    subtitle: 'Pair smiling family portraits with their loving relationships',
    category: 'MEMORY',
    targetDomain: 'Prosopagnosia Mitigation & Kinship Recognition',
    culturalTheme: 'Family Ties & Loving Kinship',
    color: 'rose',
    bgGradient: 'from-rose-600 to-pink-700',
    iconName: 'Smile',
    recommendedForMoods: ['CALM', 'SAD', 'ANXIOUS'],
    baseDifficulty: 1,
    description: 'Recognize your daughter Priyanka, granddaughter Ananya, and family friends with warm prompts.',
    instructions: 'Look at the smiling family portrait and tap their relationship (e.g. "Your Granddaughter").',
  },
  {
    id: 'game-16',
    gameKey: 'VISUAL_COLOR_SORT',
    index: 16,
    title: 'Silk Thread & Color Hue Sorting',
    subtitle: 'Organize fine handloom silk skeins by warm and cool hues',
    category: 'ATTENTION',
    targetDomain: 'Chromatic Discrimination & Visual Focus',
    culturalTheme: 'Assam Muga, Eri & Pat Silk Skeins',
    color: 'violet',
    bgGradient: 'from-violet-600 to-fuchsia-700',
    iconName: 'Sparkles',
    recommendedForMoods: ['CALM', 'TIRED', 'NEUTRAL'],
    baseDifficulty: 1,
    description: 'Arrange bright golden, crimson, forest green, and ocean blue silk threads into matching spools.',
    instructions: 'Drag or tap each silk thread to place it with its matching color family.',
  },
  {
    id: 'game-17',
    gameKey: 'LYRIC_COMPLETER',
    index: 17,
    title: 'Folk Song & Bihu Lyric Completer',
    subtitle: 'Sing along and recall classic folk verses and choruses',
    category: 'LANGUAGE',
    targetDomain: 'Phonological Memory & Long-term Retrieval',
    culturalTheme: 'Bhupen Hazarika & Traditional Bihu Geet',
    color: 'orange',
    bgGradient: 'from-orange-600 to-red-600',
    iconName: 'Radio',
    recommendedForMoods: ['HAPPY', 'CALM', 'SAD'],
    baseDifficulty: 1,
    description: 'Complete memorable lines of regional folk songs that bring back joyful youth memories.',
    instructions: 'Read the opening verse and tap the word that finishes the melody.',
  },
  {
    id: 'game-18',
    gameKey: 'CLOCK_TIME_READING',
    index: 18,
    title: 'Daily Clock & Time Reading',
    subtitle: 'Read friendly analog clock dials for daily events',
    category: 'ROUTINE',
    targetDomain: 'Temporal Reasoning & Clock Orientation',
    culturalTheme: 'Traditional Living Room Pendulum Clock',
    color: 'sky',
    bgGradient: 'from-sky-600 to-blue-700',
    iconName: 'Clock',
    recommendedForMoods: ['CALM', 'NEUTRAL'],
    baseDifficulty: 2,
    description: 'Identify what time the morning tea is served or when afternoon walks begin on the clock face.',
    instructions: 'Look at the hour and minute hands and choose the matching time.',
  },
  {
    id: 'game-19',
    gameKey: 'RECIPE_ORGANIZER',
    index: 19,
    title: 'Traditional Recipe Step Organizer',
    subtitle: 'Prepare Masor Tenga & Pitha step-by-step',
    category: 'ROUTINE',
    targetDomain: 'Executive Planning & Procedural Memory',
    culturalTheme: 'Assamese Kitchen Traditions',
    color: 'amber',
    bgGradient: 'from-amber-600 to-yellow-600',
    iconName: 'Coffee',
    recommendedForMoods: ['HAPPY', 'CALM'],
    baseDifficulty: 2,
    description: 'Arrange the steps for brewing fragrant cardamom tea or making crispy rice pitha.',
    instructions: 'Tap the cooking steps in the order you do them in the kitchen.',
  },
  {
    id: 'game-20',
    gameKey: 'NATURE_SOUNDS',
    index: 20,
    title: 'Forest Birds & Nature Sound Identifier',
    subtitle: 'Listen to forest rain, river breeze, and singing birds',
    category: 'RELAX',
    targetDomain: 'Auditory Discrimination & Grounding',
    culturalTheme: 'Brahmaputra Riverside & Hills',
    color: 'teal',
    bgGradient: 'from-teal-600 to-emerald-700',
    iconName: 'Volume2',
    recommendedForMoods: ['ANXIOUS', 'TIRED', 'CALM'],
    baseDifficulty: 1,
    description: 'Relax with soothing sounds of gentle raindrops, flowing stream waters, and chirping cuckoos.',
    instructions: 'Listen to the natural sound and tap what nature element made it.',
  },
  {
    id: 'game-21',
    gameKey: 'WORD_ASSOCIATION',
    index: 21,
    title: 'Opposites & Word Association',
    subtitle: 'Connect words with their natural opposites and partners',
    category: 'LANGUAGE',
    targetDomain: 'Semantic Network Retrieval & Speed',
    culturalTheme: 'Everyday Speech & Nature Pairs',
    color: 'purple',
    bgGradient: 'from-purple-600 to-indigo-700',
    iconName: 'MessageCircle',
    recommendedForMoods: ['HAPPY', 'CALM', 'NEUTRAL'],
    baseDifficulty: 2,
    description: 'Pair concepts like Day & Night, Warm Tea & Cold River, High Mountain & Green Valley.',
    instructions: 'Find the word that is the exact opposite of the word shown.',
  },
  {
    id: 'game-22',
    gameKey: 'TAP_RHYTHM',
    index: 22,
    title: 'Gentle Finger Tap Rhythm Match',
    subtitle: 'Tap along with the heartbeat rhythm of the folk drum',
    category: 'MOTOR',
    targetDomain: 'Fine Motor Rhythm & Motor Synchronization',
    culturalTheme: 'Dhol Rhythms & Gentle Claps',
    color: 'rose',
    bgGradient: 'from-rose-600 to-red-700',
    iconName: 'Zap',
    recommendedForMoods: ['HAPPY', 'CALM'],
    baseDifficulty: 2,
    description: 'Follow the steady, relaxing beat and tap the screen in harmony with the gentle percussion.',
    instructions: 'Tap the screen whenever the rhythmic pulse circle lights up.',
  },
  {
    id: 'game-23',
    gameKey: 'ODD_ONE_OUT',
    index: 23,
    title: 'Odd One Out Cultural Edition',
    subtitle: 'Identify which item does not belong with the others',
    category: 'SPATIAL',
    targetDomain: 'Categorical Reasoning & Outlier Detection',
    culturalTheme: 'Traditional Living Items & Wildlife',
    color: 'cyan',
    bgGradient: 'from-cyan-600 to-blue-700',
    iconName: 'Eye',
    recommendedForMoods: ['HAPPY', 'CALM', 'NEUTRAL'],
    baseDifficulty: 2,
    description: 'Look at four items (e.g. 3 musical instruments and 1 fruit) and tap the different one.',
    instructions: 'Find the item that is from a different category than the other three.',
  },
  {
    id: 'game-24',
    gameKey: 'SHADOW_MATCHER',
    index: 24,
    title: 'Shadow & Silhouette Matcher',
    subtitle: 'Match familiar objects to their dark outline shadows',
    category: 'PUZZLE',
    targetDomain: 'Visuoperceptual Discrimination & Shape Constancy',
    culturalTheme: 'Village Shapes (Japi, Tea Pot, Elephant, Lotus)',
    color: 'stone',
    bgGradient: 'from-stone-600 to-stone-800',
    iconName: 'Shield',
    recommendedForMoods: ['CALM', 'NEUTRAL'],
    baseDifficulty: 1,
    description: 'Match the colorful Japi sun hat or ceramic tea cup to its corresponding dark shadow outline.',
    instructions: 'Tap the shadow silhouette that belongs to the object on the left.',
  },
  {
    id: 'game-25',
    gameKey: 'BEAD_ABACUS',
    index: 25,
    title: 'Number Sequence & Bead Abacus',
    subtitle: 'Count and slide colorful beads in ascending order',
    category: 'PATTERN',
    targetDomain: 'Numerical Working Memory & Counting',
    culturalTheme: 'Handmade Wooden Abacus & Beads',
    color: 'amber',
    bgGradient: 'from-amber-600 to-orange-700',
    iconName: 'Layers',
    recommendedForMoods: ['HAPPY', 'CALM'],
    baseDifficulty: 2,
    description: 'Count the wooden beads on the frame and tap the missing number in sequence.',
    instructions: 'Count the beads shown and pick the correct total or next number.',
  },
  {
    id: 'game-26',
    gameKey: 'PATH_NAVIGATOR',
    index: 26,
    title: 'Village Path & Direction Finder',
    subtitle: 'Guide the traveler home along the peaceful village trail',
    category: 'SPATIAL',
    targetDomain: 'Spatial Navigation & Route Planning',
    culturalTheme: 'Bamboo Grove & Paddy Field Pathways',
    color: 'emerald',
    bgGradient: 'from-emerald-600 to-green-800',
    iconName: 'Compass',
    recommendedForMoods: ['HAPPY', 'CALM'],
    baseDifficulty: 2,
    description: 'Choose Left, Right, or Straight at simple garden crossroads to reach the tea pavilion.',
    instructions: 'Tap the direction arrows to guide the gentle walk towards home.',
  },
  {
    id: 'game-27',
    gameKey: 'EMOTION_MATCHER',
    index: 27,
    title: 'Emotion & Expression Matcher',
    subtitle: 'Identify joyful, serene, and calm feelings in faces',
    category: 'LANGUAGE',
    targetDomain: 'Social Cognition & Emotion Recognition',
    culturalTheme: 'Warm Human Connections & Smiles',
    color: 'pink',
    bgGradient: 'from-pink-600 to-rose-700',
    iconName: 'Smile',
    recommendedForMoods: ['CALM', 'SAD', 'ANXIOUS'],
    baseDifficulty: 1,
    description: 'Recognize joyful smiles, peaceful calm gazes, and friendly reassuring expressions.',
    instructions: 'Look at the friendly face and select the emotion they are expressing.',
  },
  {
    id: 'game-28',
    gameKey: 'CUP_BALANCE',
    index: 28,
    title: 'Tea Cup Stacking & Weight Balance',
    subtitle: 'Stack clay cups gently from largest to smallest',
    category: 'PUZZLE',
    targetDomain: 'Visuomotor Planning & Size Seriation',
    culturalTheme: 'Clay Pottery & Tea Cups (Kulhad)',
    color: 'amber',
    bgGradient: 'from-amber-700 to-stone-700',
    iconName: 'Coffee',
    recommendedForMoods: ['CALM', 'NEUTRAL'],
    baseDifficulty: 2,
    description: 'Stack three clay tea cups neatly by placing the larger cup at the base and smaller on top.',
    instructions: 'Tap the cups in order from widest to smallest to build a sturdy stack.',
  },
  {
    id: 'game-29',
    gameKey: 'OBJECT_FUNCTION',
    index: 29,
    title: 'Daily Object Function Pairing',
    subtitle: 'Match everyday tools with what they are used for',
    category: 'ROUTINE',
    targetDomain: 'Semantic Utility & Object Function',
    culturalTheme: 'Traditional Home & Kitchen Tools',
    color: 'teal',
    bgGradient: 'from-teal-600 to-sky-700',
    iconName: 'CheckCircle2',
    recommendedForMoods: ['CALM', 'NEUTRAL'],
    baseDifficulty: 1,
    description: 'Pair the Brass Kettle with Brewing Tea, the Japi with Shading Sun, and the Comb with Hair Care.',
    instructions: 'Tap the tool, then tap what it helps you do.',
  },
  {
    id: 'game-30',
    gameKey: 'MANDALA_COLORING',
    index: 30,
    title: 'Meditative Mandala & Rangoli Coloring',
    subtitle: 'Relaxing 1-tap color filling on peaceful floral motifs',
    category: 'RELAX',
    targetDomain: 'Visuomotor Mindfulness & Anxiety Reduction',
    culturalTheme: 'Courtyard Floral Rangoli & Motifs',
    color: 'purple',
    bgGradient: 'from-purple-600 to-pink-700',
    iconName: 'Sparkles',
    recommendedForMoods: ['ANXIOUS', 'TIRED', 'SAD', 'CALM', 'NEUTRAL'],
    baseDifficulty: 1,
    description: 'Tap beautiful floral petals to fill them with saffron, lotus pink, and emerald green colors.',
    instructions: 'Select your favorite color and tap the petal sections to bring the artwork to life.',
  },
];
